//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tweets = new HashSet<Tweet>();
        }
    
        public int Id { get; set; }
        public string Full_name { get; set; }
        public string Email { get; set; }
        public string Phone_number { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public Nullable<System.DateTime> Date_of_registration { get; set; }
        public string Password { get; set; }
        public string Location { get; set; }
        public string Avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tweet> Tweets { get; set; }
    }
}
